### ISSUE TITLE
A bit lost..

### ISSUE THREAD

**Issue by lassebenni** [SOMAStandard/soma_b2b_saas#10]
Hi @ergest , I love the idea for this framework! Working as an analyst we often have to repeat the work and a standard would help a lot!

That being said, I appreciate the hard work of creating all the models, but I am missing a guide/example to better understand the models. Taking `ga_cube_revenue_growth_rate.sql` for instance, I can see the SQL, and deduce that the idea is to track the revenue growth rate but I don't immediately understand the fields that are being selected, or when to use this.

Do you plan on describing the ideas behind the models/metrics, or creating a guide per business process, or what is your view on spreading the use of the framework?

**Comment by ergest** [comment]
Yes there’s a website coming soon that will explain the formulas behind the code. Stay tuned and follow me on Twitter or LinkedIn
